{
 "title": "Consumers Lag",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumer Group 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_consumer_lag{consumerGroup=\"my-consumer-group-2\"}"
    }
   ]
  },
  {
   "title": "All Consumer Lags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "librdkafka_consumer_lag" }
   ]
  },
  {
   "title": "Consumer Group 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_consumer_lag{consumerGroup=\"my-consumer-group-1\"}"
    }
   ]
  }
 ]
}